version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: okr
      MYSQL_ROOT_PASSWORD: root
    container_name: 'okr-mysql'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - app-net

  redis:
    image: redis:3.2.9
    ports:
      - "6379:6379"
    container_name: 'okr-redis'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge